# Generated by Django 3.2.8 on 2021-12-07 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepause',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='activepause',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='active-pauses/images/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='activepause',
            name='icon_svg',
            field=models.FileField(blank=True, null=True, upload_to='active-pauses/icons/', verbose_name='Icono en SVG'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del video')),
                ('video', models.FileField(blank=True, null=True, upload_to='active-pauses/videos/', verbose_name='Video')),
                ('active_pause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activepause', verbose_name='Pausa activa')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
